// TYPE_CITY TYPE_ZONE TYPE_DUNGEON
TELEPORT_CASE WI_WORLD_MADRIGAL 6970 100 3337 TYPE_CITY "Flaris" "teleportFlaris.png" "Just a flaris"
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 8396 100 3673 TYPE_CITY "Saint Morning" "teleportSaint.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 3818 59 4425 TYPE_CITY "Darkon 2" "teleportDarkon2.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 7244 66 9135 TYPE_CITY "Eillun" "teleportEillun.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 9271 99 3703 TYPE_ZONE "Garden of Rhisis" "teleportGarden.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 5573 75 3905 TYPE_ZONE "Darkon 1" "teleportDarkon1.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 3860 38 3243 TYPE_ZONE "Darkon 3" "teleportDarkon3.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 5950 100 5400 TYPE_ZONE "Shaduwar" "teleportShaduwar.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 7066 100 6569 TYPE_ZONE "Valley of the Risen" "teleportValley.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6054 70 9427 TYPE_ZONE "Bahara Desert" "teleportBahara.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6942 100 3104 TYPE_ZONE "Collecting Area" "teleportCollect.png" ""
{
}

TELEPORT_CASE WI_WORLD_ARENA 540 139 486 TYPE_ZONE "Arena" "teleportArena.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 3341 100 1882 TYPE_ZONE "Volcane" "teleportVolcane.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 5267 100 4713 TYPE_DUNGEON "The Wilds" "teleportWilds.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 4919 100 3455 TYPE_DUNGEON "The Savage Wilds" "teleportWilds.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 2783 150 5244 TYPE_DUNGEON "Isle of Dreams" "teleportIsle.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 2705 150 5235 TYPE_DUNGEON "Isle of Nightmares" "teleportIsle.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 1842 100 2754 TYPE_DUNGEON "Cove of the Ancients" "teleportCove.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 2038 100 2267 TYPE_DUNGEON "Abyssal Cove of the Ancients" "teleportCove.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 5175 100 5279 TYPE_DUNGEON "Les Brittania S" "teleportShip.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6576 100 5074 TYPE_DUNGEON "La Christiana A" "teleportShip.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6641 58 6460 TYPE_DUNGEON "Aminus" "teleportAminus.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6788 100 6062 TYPE_DUNGEON "Cursed Aminus" "teleportAminus.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 6374 100 8047 TYPE_DUNGEON "Catacombs" "teleportCatacombs.png" ""
{  
}

TELEPORT_CASE WI_WORLD_MADRIGAL 8263 69 9371 TYPE_DUNGEON "Ankou's Asylum" "teleportAnkou.png" ""
{
}

TELEPORT_CASE WI_WORLD_MADRIGAL 5732 88 8155 TYPE_DUNGEON "Kalgas Cave" "teleportKalgas.png" ""
{
}