number 33
texture "Theme\Default\ImgNavObj.bmp" 0xffff00ff
serialize 4  5  5  0   0 0 0 // 큰 직업 아이콘 
serialize 2  5  5  0   5 0 0 // 큰 직업 아이콘 
pos 7 7  9 9 h
serialize 6 12 12  0  20 0 0 // 작은 직업 아이콘 
serialize 7 12 12  0  32 0 0 // 작은 직업 아이콘 
serialize 4 16 16 20  0 0 0 // 퀘스트 마크 
serialize 3 16 16 0  44 0 0 // 노란색 퀘스트
serialize 3 16 16 0  60 0 0 // 연두색 퀘스트 
serialize 3 16 16 0  76 0 0 // 붉은색 퀘스트